import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "https://esm.sh/resend@4.0.0";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface EmailRequest {
  email: string;
  result: any;
}

const handler = async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { email, result }: EmailRequest = await req.json();
    console.log("Sending email to:", email);

    const emailResponse = await resend.emails.send({
      from: "SafeLens AI <onboarding@resend.dev>",
      to: [email],
      subject: `SafeLens AI Analysis Report - ${result.overallRisk}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background-color: #0a0a0a; color: #00ff94; padding: 20px; border: 1px solid #00ff94;">
          <h1 style="color: #00ff94; text-align: center; margin-bottom: 20px;">🛡️ SafeLens AI Security Report</h1>
          
          <div style="background-color: #1a1a1a; border: 1px solid #333; padding: 15px; margin-bottom: 20px;">
            <h2 style="color: #00ff94; margin-top: 0;">Overall Risk: ${result.overallRisk}</h2>
            <p style="font-size: 16px; line-height: 1.6;">${result.summary}</p>
          </div>

          ${result.threats?.length > 0 ? `
          <div style="background-color: #1a1a1a; border: 1px solid #333; padding: 15px; margin-bottom: 20px;">
            <h3 style="color: #ff4444;">⚠️ Detected Threats:</h3>
            <ul style="padding-left: 20px;">
              ${result.threats.map((threat: string) => `<li style="margin-bottom: 8px;">${threat}</li>`).join('')}
            </ul>
          </div>
          ` : ''}

          ${result.recommendations?.length > 0 ? `
          <div style="background-color: #1a1a1a; border: 1px solid #333; padding: 15px; margin-bottom: 20px;">
            <h3 style="color: #00ff94;">✅ Recommendations:</h3>
            <ul style="padding-left: 20px;">
              ${result.recommendations.map((rec: string) => `<li style="margin-bottom: 8px;">${rec}</li>`).join('')}
            </ul>
          </div>
          ` : ''}

          <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #333;">
            <p style="color: #888; font-size: 14px;">Generated by SafeLens AI - Your Security Guardian</p>
          </div>
        </div>
      `,
    });

    console.log("Email sent successfully:", emailResponse);

    return new Response(JSON.stringify({ success: true, emailResponse }), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        ...corsHeaders,
      },
    });
  } catch (error: any) {
    console.error("Error in send-report function:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);
